@echo off

echo cleaning...
call make dist-clean
echo building Makefile...
call templates\build DB.cfg
echo making dist...
call make dist
echo making exe...
call make exe
echo making zip...
call make zip
echo Done.
pause
