#!/bin/sh

#echo "-----Normalizing Regular UFO..."
#echo "-----Updating production names in Regular..."
#psfsetpsnames -p checkfix=fix -i source/glyph_data.csv source/masters/DaiBannaSILMaster-Regular.ufo -x

#echo "-----Updating glyph orders in Regular..."
#psfsetglyphorder -q --header sort_final_cdg -i source/glyph_data.csv source/masters/DaiBannaSILMaster-Regular.ufo -p backup=False -x

echo "-----Normalizing UFOs..."
psfnormalize -p checkfix=fix source/masters/DaiBannaSILMaster-Regular.ufo          &
psfnormalize -p checkfix=fix source/masters/DaiBannaSILMaster-ExtraBold.ufo        &
psfnormalize -p checkfix=fix source/masters/DaiBannaSILMaster-Italic.ufo           &
psfnormalize -p checkfix=fix source/masters/DaiBannaSILMaster-ExtraBoldItalic.ufo  &
wait

echo "-----Create WOFF metadata file..."
psfmakewoffmetadata -n "DaiBannaSIL" -i org.sil.fonts -o source/DaiBannaSIL-WOFF-metadata.xml source/masters/*-Regular.ufo

#echo "-----Rebuilding composites..."
psfbuildcomp -i source/composites.txt -c -n source/masters/DaiBannaSILMaster-Regular.ufo -p backup=False
psfbuildcomp -i source/composites.txt -c -n source/masters/DaiBannaSILMaster-ExtraBold.ufo -p backup=False
psfbuildcomp -i source/composites.txt -c -n source/masters/DaiBannaSILMaster-Italic.ufo -p backup=False
psfbuildcomp -i source/composites.txt -c -n source/masters/DaiBannaSILMaster-ExtraBoldItalic.ufo -p backup=False

echo "-----Syncing glyph orders, psnames, and other metadata to other UFOs..."
psfsyncmasters -q source/DaiBannaSILUpright.designspace source/DaiBannaSILItalic.designspace

echo "-----Preflight completed!"
