#!/bin/sh

psffixffglifs -p checkfix=fix source/masters/DaiBannaSIL-Light.ufo &
psffixffglifs -p checkfix=fix source/masters/DaiBannaSIL-Bold.ufo &
psffixffglifs -p checkfix=fix source/masters/DaiBannaSIL-LightItalic.ufo &
psffixffglifs -p checkfix=fix source/masters/DaiBannaSIL-BoldItalic.ufo &
wait
./preflight
