#!/bin/sh

CFGFILE=$1
if [ $CFGFILE = '-d' ] ; then
    CFGFILE='package.cfg';
    DEBUG='-d';
elif [ -z $CFGFILE ] ; then
    CFGFILE='package.cfg';
else
    DEBUG=$2;
fi
DIR=`dirname $0`
perl $DEBUG $DIR/autosub -c $CFGFILE -c $DIR/keyman.cfg -d . -x \~ $DIR/keyboards

